name: Update Google Calendar

on:
  schedule:
    - cron: "0 4,18 * * *"  # Exécution à 04:00 et 18:00 UTC
  workflow_dispatch:  # Déclenchement manuel

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Timeout de sécurité

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mise à jour vers v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Mise à jour vers v5
        with:
          python-version: "3.11"  # Version Python explicite plutôt qu'un secret

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver xvfb
          sudo chmod +x /usr/bin/chromedriver  # Assure les permissions d'exécution

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create configuration files
        run: |
          echo '${{ secrets.ENV }}' > .env
          mkdir -p google
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google/client_secret.json

      - name: Run script
        env:
          CY_USERNAME: ${{ secrets.CY_USERNAME }}
          CY_PASSWORD: ${{ secrets.CY_PASSWORD }}
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          python cyCalendar.py

      - name: Upload logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: |
            *.log
            ./*.txt
          retention-days: 5
